exclude: "(migrations/versions/)"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Backend hooks
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --imports=sqlalchemy,pydantic
        types: [file, python]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        types: [file, python]
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        files: src/
        # B008: Do not perform function calls in argument defaults. (FastAPI relies heavily on these)
        # F401: Unused imports (kinda annoying, remove this rule if you want to enforce it)
        args: [--max-line-length=131, --ignore, "B008,W503"]

        types: [file, python]
        additional_dependencies:
          [flake8-comprehensions, flake8-bugbear]
