version: "3.9"
services:
  web:
    container_name: ms_app
    build: .
    volumes:
      - .:/code
    # command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8001:8000
    environment:
      - APP_ENV=development
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=test_db
      - TEST_DATABASE_NAME=test_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: ms_db
    image: postgres:14
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    healthcheck:
      test: "exit 0"
